### ISSUE TITLE
`fr640_3r-3v-example` sometimes crashes in the test website

### ISSUE THREAD

**Issue by camdendotlol** [cu-mkp/editioncrafter#57]
Ever since #55 was merged to `dev`, the old example document intermittently has errors. It appears to be some sort of race condition where it tries to access an attribute of the folio before it's loaded, but it happens so intermittently that it's hard to debug, and it doesn't happen locally (probably due to the faster load times accessing localhost).

See https://cu-mkp.github.io/editioncrafter/?path=/story/editioncrafter--testing-fr-640

**Comment by NickLaiacona** [comment]
When I open the translation for folio 3r, I'm getting this error now both on the deployed site and local. It only seems to happen for the fr640 example and not for Taos:

<img width="1330" alt="Screen Shot 2023-09-04 at 11 32 09 AM" src="https://github.com/cu-mkp/editioncrafter/assets/11439/d2441ce9-1959-40b4-a819-24349cb04e97">

**Comment by NickLaiacona** [comment]
I think this is resolved @camdendotlol ? Please close this issue if so.

**Comment by camdendotlol** [comment]
The original issue is not. I still see it occasionally when switching between components in Storybook.

The error in your screenshot was unrelated and is indeed fixed, but we should leave this issue open.
